site_name: Bpod Wiki testing
copyright: Copyright &copy; 2016 - 2023 Sanworks LLC  # is this accurate?
repo_url: https://github.com/sanworks/Bpod_Gen2  # the top right's repo link
repo_name: Sanworks/Bpod_Gen2
edit_uri: https://github.com/ogeesan/bpod-docs-testing/tree/main/docs/  # where the features content.action.edit and content.action.view link to

nav:
  - Home: index.md
  - User Guide:
    - user-guide/general-concepts.md
    - user-guide/function-reference.md 
    - user-guide/serial-interfaces.md
    - user-guide/modules.md
  - Modules:
    - Plugins:
      - module-documentation/analog-input-module.md
      - module-documentation/audioplayer.md
      - module-documentation/dds-module.md
      - module-documentation/hifi-module.md
      - module-documentation/I2C-messenger-module.md
      - module-documentation/pulsepal-module.md
      - module-documentation/rotary-encoder-module.md
      - module-documentation/waveplayer.md
    - Serial Interfaces:
      - serial-interfacesanalogue-input-module-serial-interface.md
      - serial-interfacesaudioplayer-serial-interface.md
      - serial-interfacesblink-module-serial-interface.md
      - serial-interfaceshifi-module-serial-interface.md
      - serial-interfacesport-array-module-serial-interface.md
      - serial-interfacesrotary-encoder-module-serial-interface.md
      - serial-interfacesvalve-module-serial-interface.md
      - serial-interfaceswaveplayer-serial-interface.md
  - Assembly:
    - General Guides and Installation:
      - install-and-update/installing-bpod.md
      - user-guide/general-build-guide.md
      - user-guide/bench-testing-bpod.md
    - Software and Firmware Updates:
      - install-and-update/software-update.md
      - install-and-update/firmware-update.md
    - State Machines:
      - assembly/state-machine-assembly-0_5.md
      - assembly/state-machine-assembly-0_9-1_0.md
      - assembly/state-machine-assembly-2_3-2_4.md
      - assembly/state-machine-assembly-2_5.md
      - assembly/state-machine-assembly-2+.md
    - Modules:
      - assembly/analog-input-module-assembly.md
      - assembly/analog-output-module-assembly.md
      - assembly/arduino-shield-0-5-assembly.md
      - assembly/arduino-shield-gen2-assembly.md
      - assembly/dds-module-assembly.md
      - assembly/ethernet-module-assembly.md
      - assembly/hifi-module-assembly.md
      - assembly/lickometer-assembly.md
      - assembly/mouse-behavior-port-assembly.md
      - assembly/mouse-box-assembly.md
      - assembly/neuralynx-sync-board-assembly.md
      - assembly/open-ephys-module-assembly.md
      - assembly/port-array-module-assembly.md
      - assembly/port-breakout-board-assembly.md
      - assembly/raspberry-pi-shim-assembly.md
      - assembly/rotary-encoder-module-assembly.md
      - assembly/snes-module-assembly.md
      - assembly/teensy-shield-assembly.md
      - assembly/valve-driver-module-assembly.md
  - External links:
    - "Sanworks": "https://sanworks.io"
    - "Forums": "https://sanworks.io/forums"
    - "GitHub": "https://github.com/sanworks/Bpod_Gen2"

markdown_extensions:
  - admonition  # callouts/alerts
  - attr_list
  - footnotes
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins: 
  - search

theme:
  name: material
  features:
    - navigation.sections # use titles rather than expanding items
    # - navigation.expand # expand all items
    - navigation.indexes
    - content.action.edit
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  palette:
  # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  logo: https://avatars.githubusercontent.com/u/17090284?v=4
  # 
  #favicon: https://avatars.githubusercontent.com/u/17090284?v=4
  # favicon should be different color scheme to sanworks.io favicon
  icon:
    repo: fontawesome/brands/github

extra_css:
  - https://fonts.googleapis.com/css2?family=Aldrich