== A brief overview of Bpod serial interfaces
A "serial interface" is a communication protocol that involves sending and receiving data one byte at a time, serially. 

This allows computer software (e.g. MATLAB, Python) to communicate with the hardware via USB, or for the hardware to communicate with other hardware via serial ports (via ethernet CAT5e cables).

Bpod uses the https://github.com/sanworks/Bpod_Gen2/blob/master/Functions/Internal%20Functions/ArCOM/ArCOMObject_Bpod.m[ArCOM] object to interact with hardware over USB.

[source, mermaid]
....
flowchart
arcom(ArCOM Object)
modulefunction(MATLAB Module Wrapper)
moduleserial(Module serial message process)
statemachine(Bpod State Machine)
module(Module)

modulefunction --> arcom
statemachine --> moduleserial
arcom --> moduleserial
moduleserial --> module

....


NOTE: The module functions (e.g. `BpodWavePlayer`) utilise the `ArCOM` object to communicate with the hardware via serial interface.

== State machine serial interface

- Firmware v17 https://sites.google.com/site/bpoddocumentation/user-guide/serial-interfaces/statemachineserialinterface?authuser=0[State Machine Serial Interfaec]
- Firmware v18-22 https://sites.google.com/site/bpoddocumentation/user-guide/serial-interfaces/fsm_interface_v18?authuser=0[State MAchine Serial Interface]




== Module serial interfaces

There are a few things


This is how it works